In [1]:
import numpy as np

In [6]:
list1=[10,20,30,40]
array1=np.array(list1)
array1

array([10, 20, 30, 40])

In [7]:
array1**2

array([ 100,  400,  900, 1600], dtype=int32)

In [9]:
array1*5

array([ 50, 100, 150, 200])

In [12]:
np.sqrt(array1)

array([3.16227766, 4.47213595, 5.47722558, 6.32455532])

In [13]:
list2=[3,6,9,12,15,18,21,24,27]
array2=np.array(list2)
array2

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27])

In [14]:
list3=[11,12,13,14,15,16,17,18,19]
array3=np.array(list3)
array3

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
array2*array3

array([ 33,  72, 117, 168, 225, 288, 357, 432, 513])

In [16]:
process1=np.load("process1.npy")
process2=np.load("process2.npy")
process3=np.load("process3.npy")
process4=np.load("process4.npy")
process5=np.load("process5.npy")

In [18]:
array4=np.vstack([process1,process2,process3,process4,process5])
array4

array([[52, 12, 81,  0, 58],
       [96,  4, 61, 16, 43],
       [38, 96, 45, 17, 58],
       [97, 21, 22, 25,  6],
       [77,  6, 19,  2, 74]])

In [28]:
array4[:5,:1].mean()

72.0

In [34]:
array4[:5,1:2].mean()

27.8

In [35]:
array4[:5,2:3].mean()

45.6

In [36]:
array4[:5,3:4].mean()

12.0

In [37]:
array4[:5,4:5].mean()

47.8

### Individual Project 2, Ryan Fox, Version 1, Spring DS160